/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteChoreArgs } from "./DeleteChoreArgs";
import { ChoreFindManyArgs } from "./ChoreFindManyArgs";
import { ChoreFindUniqueArgs } from "./ChoreFindUniqueArgs";
import { Chore } from "./Chore";
import { ChoreService } from "../chore.service";

@graphql.Resolver(() => Chore)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ChoreResolverBase {
  constructor(
    protected readonly service: ChoreService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Chore",
    action: "read",
    possession: "any",
  })
  async _choresMeta(
    @graphql.Args() args: ChoreFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Chore])
  @nestAccessControl.UseRoles({
    resource: "Chore",
    action: "read",
    possession: "any",
  })
  async chores(
    @graphql.Args() args: ChoreFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Chore[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Chore",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Chore, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Chore",
    action: "read",
    possession: "own",
  })
  async chore(
    @graphql.Args() args: ChoreFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Chore | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Chore",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Chore)
  @nestAccessControl.UseRoles({
    resource: "Chore",
    action: "delete",
    possession: "any",
  })
  async deleteChore(
    @graphql.Args() args: DeleteChoreArgs
  ): Promise<Chore | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
