/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateFundingSourceArgs } from "./CreateFundingSourceArgs";
import { UpdateFundingSourceArgs } from "./UpdateFundingSourceArgs";
import { DeleteFundingSourceArgs } from "./DeleteFundingSourceArgs";
import { FundingSourceFindManyArgs } from "./FundingSourceFindManyArgs";
import { FundingSourceFindUniqueArgs } from "./FundingSourceFindUniqueArgs";
import { FundingSource } from "./FundingSource";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { FundingSourceService } from "../fundingSource.service";

@graphql.Resolver(() => FundingSource)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FundingSourceResolverBase {
  constructor(
    protected readonly service: FundingSourceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FundingSource",
    action: "read",
    possession: "any",
  })
  async _fundingSourcesMeta(
    @graphql.Args() args: FundingSourceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [FundingSource])
  @nestAccessControl.UseRoles({
    resource: "FundingSource",
    action: "read",
    possession: "any",
  })
  async fundingSources(
    @graphql.Args() args: FundingSourceFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FundingSource[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "FundingSource",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => FundingSource, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FundingSource",
    action: "read",
    possession: "own",
  })
  async fundingSource(
    @graphql.Args() args: FundingSourceFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FundingSource | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "FundingSource",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => FundingSource)
  @nestAccessControl.UseRoles({
    resource: "FundingSource",
    action: "create",
    possession: "any",
  })
  async createFundingSource(
    @graphql.Args() args: CreateFundingSourceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FundingSource> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "FundingSource",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FundingSource"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => FundingSource)
  @nestAccessControl.UseRoles({
    resource: "FundingSource",
    action: "update",
    possession: "any",
  })
  async updateFundingSource(
    @graphql.Args() args: UpdateFundingSourceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FundingSource | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "FundingSource",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FundingSource"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FundingSource)
  @nestAccessControl.UseRoles({
    resource: "FundingSource",
    action: "delete",
    possession: "any",
  })
  async deleteFundingSource(
    @graphql.Args() args: DeleteFundingSourceArgs
  ): Promise<FundingSource | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "FundingSource",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: FundingSource,
    @graphql.Args() args: UserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
